### ISSUE TITLE
ecs_service planning

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.aws#1142]
### Summary

`ecs_service` needs some care

- [ ] make `ecs_cluster` integration test work again
- [ ] implement waiters: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#waiters
- [ ] limit `placement_constraints`  to max 10 (verify what docs told)
- [ ] https://github.com/ansible-collections/community.aws/issues/1137
- [ ] [ Support force_new_deployment without having to specify a task definition](https://github.com/ansible-collections/community.aws/issues/1106)
- [ ] [ecs_service cannot handle distinctInstance Placement Constraint](https://github.com/ansible-collections/community.aws/issues/1058)
- [ ] [circuit breaker settings missing in ecs_service module](https://github.com/ansible-collections/community.aws/issues/921)

### Issue Type

Bug Report

### Component Name

ecs_service

### Ansible Version

```console (paste below)
$ ansible --version

```
ac

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```
ca

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```
ca

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

nothing

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
bot_skip

**Comment by markuman** [comment]
everyone who is bored can join

**Comment by jatorcasso** [comment]
@markuman I can poke at a few of these after #1145 gets merged

**Comment by jatorcasso** [comment]
@markuman where are waiters needed here? are there specific test cases I can look at to validate the waiters do their job?

**Comment by markuman** [comment]
> @markuman where are waiters needed here? are there specific test cases I can look at to validate the waiters do their job? I see for scaling down services

yes. one case is when the service is `state: absent`, in must wait until the service is inactive.   
it would make this retry https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/ecs_cluster/tasks/main.yml#L983-L991 superfluous, because the cluster can only be removed when no service is available anymore.

another case is when the desired_count changes.  https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/ecs_cluster/tasks/main.yml#L301-L319  
or when the service is created. it must wait until the service is table: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Waiter.ServicesStable  
this would also solves this PR: https://github.com/ansible-collections/community.aws/pull/91

**Comment by markuman** [comment]
something else that might be need to be discussed is the format of the task_definition.

The input format is documented like this: https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/ecs_service.py#L214

```yml
    task_definition: 'new_cluster-task:1'
```

But the output is returning just the arn of the task_definition: 
* https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/ecs_service.py#L308-L309
* https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/ecs_service.py#L424-L425

```yml
    taskDefinition: arn:aws:ecs:eu-central-1:123456789:task-definition/new_cluster-task:1
```

Shall we support both as valid input formats?

**Comment by tremble** [comment]
> Shall we support both as valid input formats?

Having dealt with all sorts of cross-account fun in the past few years, I'm a fan of supporting full ARNs in addition to just the names.

**Comment by jatorcasso** [comment]
@ingmarfjolla this could be a good first contribution for ya

**Comment by alinabuzachis** [comment]
@markuman Can you please check what's missing in here?
